### ISSUE TITLE
[FEAT] Dashboard from Homeassistant Data

### ISSUE THREAD

**Issue by starsoccer** [lux4rd0/kidde-collector#4]
This may be outside the scope of the project, but since I know alot of folks myself included are using homeassistant. It would be convenient to also offer the dashboard making use of the data HA already exports via influxdb instead of needing to run another container.

**Comment by lux4rd0** [comment]
Hi @starsoccer, Thanks for the thoughtful suggestion! I can see the appeal of leveraging Home Assistant’s InfluxDB export, especially given how many of us already use it in our setups.

The primary aim of this project is to provide a dedicated data collector with Grafana dashboards rather than to create flexible Grafana dashboards for various backends. While integrating directly with HA's InfluxDB data might seem straightforward, it brings some unique challenges. From my experience (and I use HA extensively, managing hundreds of devices and integrations), the exported data structure from HA's InfluxDB often needs to be more consistent and heavily customized. This variability means what works for one setup may be entirely unsuitable for another, making standardized support quite complex.

That said, I’m open to exploring ways to make the collector as versatile as possible without compromising its core purpose. Thanks again for the input—it's great to know the directions that could benefit users like you!

**Comment by starsoccer** [comment]
So I played around a bit with the dashboard and most of the data does seem to be there to make the dashboards work. The main issue I have encountered is that home assistant exposes the data using the measurement or the sensor name which in some cases can be very vague and makes showing a list of all the sensors in one place difficult without a hard coded list or prefixing all entities with kiddie or some other schema

**Comment by lux4rd0** [comment]
@starsoccer - I've enjoyed making a LOT of Grafana dashboards for HA, both for the Prometheus and InfluxDB exports. They can be configured based on Friendly Name, Class Name, entity, etc. Still, it also depends on the integration's naming and data dictionary and both exporter configurations in HA. I have 4800 entities across three home assistance platforms - and while I suppose I could be amazingly prescriptive and say, "Name all of your devices like this or like that, and here is your entity structure," - it's just not where I'm spending my limited time right now. :) How does "`sensor.basement_air_pressure`" fit into my entire schema of devices when it doesn't even tell me it's related to Kidde devices? Because how would you ever filter based on the exporter's "flexibility"?

That said, if I get a few minutes, I'll take a look. :)
